modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
[[mods]]
  modId = "creatania"
  version = "${file.jarVersion}"
  displayName = "creatania"
  credits = "ClaudiusMinimums: art, ideas, documentation"
  authors = "zaftnotameni"
  description = '''
Connecting the world of Botania and Create
'''
[[dependencies.creatania]]
  modId = "forge"
  mandatory = true
  versionRange = "[40,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.18.2,1.19)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "botania"
  mandatory = true
  versionRange = "[1.18.2-435,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "create"
  mandatory = true
  versionRange = "[0.5.0.i,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "jei"
  mandatory = true
  versionRange = "[9.5.2.136,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "kubejs"
  mandatory = true
  versionRange = "[1802,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "rhino"
  mandatory = true
  versionRange = "[1802,)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.creatania]]
  modId = "ponderjs"
  mandatory = true
  versionRange = "[1.18.2,)"
  ordering = "NONE"
  side = "BOTH"